services:
- type: web
  name: line-bot-python-flask-NBB
  env: python
  buildCommand: cd src;pip install gunicorn -r requirements.txt
  startCommand: cd src;gunicorn app_with_handler:app
  plan: free
  autoDeploy: false
  envVars:
  - key: LINE_CHANNEL_ACCESS_TOKEN
    sync: false
  - key: LINE_CHANNEL_SECRET
    sync: false
  - key: GOOGLE_SHEET_ID
    sync: false
